### ISSUE TITLE
shutting down server

### ISSUE THREAD

**Issue by SliderKP** [gvlfm78/BukkitOldCombatMechanics#102]
error: [13:42:42] [Server thread/ERROR]: Could not pass event ArmourEquipEvent to OldCombatMechanics v1.5.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at com.codingforcookies.armourequip.ArmourListener.onInventoryClick(ArmourListener.java:146) [OldCombatMechanics.jar:?]
	at sun.reflect.GeneratedMethodAccessor550.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.comphenix.example.NbtFactory$NbtCompound.getLong(NbtFactory.java:129) ~[?:?]
	at com.comphenix.example.Attributes$Attribute.getUUID(Attributes.java:160) ~[?:?]
	at com.comphenix.example.Attributes.remove(Attributes.java:298) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.apply(ModuleOldArmourStrength.java:144) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onArmourEquip(ModuleOldArmourStrength.java:35) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[overcraft.jar:git-Spigot-7d78b81-70bc70b]
	... 23 more

**Comment by gvlfm78** [comment]
This seems to be the same as issue #57 . Please check that to see how it was solved and tell us if your situation is different.
