### ISSUE TITLE
OCM Showing up red on plugin list

### ISSUE THREAD

**Issue by LikeableGaming** [gvlfm78/BukkitOldCombatMechanics#109]
- Paper Spigot 1.10.2
- OCM 1.6
- Config.yml: https://pastebin.com/2U0rbQDD

**Comment by EBatuzay** [comment]
same in Paper Spigot 1.12
OCM 1.6.0
`[Server thread/ERROR]: Error occurred while enabling OldCombatMechanics v1.6.0 (Is it up to date?)
java.lang.NullPointerException: null
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.run(SpigotUpdateChecker.java:75) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.<init>(SpigotUpdateChecker.java:49) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.<init>(OCMUpdateChecker.java:28) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.registerAllEvents(OCMMain.java:120) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [patched_1.12.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1169]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by gvlfm78** [comment]
Try setting the update checker in the config to bukkit. I don't know what happened to the spigot update checker but it appears to be broken.

**Comment by gvlfm78** [comment]
Can you please try with the [latest test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/)

**Comment by EBatuzay** [comment]
working! thx
