### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by md-cz** [gvlfm78/BukkitOldCombatMechanics#110]
Error in console:
` Error occurred while enabling OldCombatMechanics v1.6.0 (Is it up to date?)
java.lang.NullPointerException: null
at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.run(SpigotUpdateChecker.java:75) ~[?:?]
at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.<init>(SpigotUpdateChecker.java:49) ~[?:?]
at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.<init>(OCMUpdateChecker.java:28) ~[?:?]
at gvlfm78.plugin.OldCombatMechanics.OCMMain.registerAllEvents(OCMMain.java:120) ~[?:?]
at gvlfm78.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:54) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:751) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.Bukkit.reload(Bukkit.java:525) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-5340a52-27b8bf9]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

Config: 
https://pastebin.com/RsD2XRYR
Version:
1.12.1-R0.1-SNAPSHOT
OCM: 
v1.6.0

**Comment by gvlfm78** [comment]
Try setting the update checker in the config to bukkit. I don't know what happened to the spigot update checker but it appears to be broken.

**Comment by iMaarten** [comment]
Changing it to bukkit does not work nor does putting it to false.

**Comment by gvlfm78** [comment]
Can you please try with the [latest test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/)

**Comment by iMaarten** [comment]
Latest dev build fixes the problem.
