### ISSUE TITLE
Cooldown not working as intended while using ViaVersion

### ISSUE THREAD

**Issue by x9nico** [gvlfm78/BukkitOldCombatMechanics#135]
Hi, possible to add pvp support for ViaVersion please ?

**Comment by detobel36** [comment]
What isn't support ?      
I already use OCM with ViaVersion and I haven't any problem

**Comment by x9nico** [comment]
For cooldown

**Comment by Rayzr522** [comment]
What about the cooldown is not supported with ViaVersion? Also, what server version are you running?

**Comment by x9nico** [comment]
1.8 server version.
The players on 1.9-1.12 don't have the same has the 1.8

**Comment by gvlfm78** [comment]
Do you mean they have different cooldowns? Who has what cooldown?

**Comment by x9nico** [comment]
They have the cooldown as the 1.9 and 1.8 don't have cooldown.

**Comment by gvlfm78** [comment]
What setting do you have in your config.yml under the cooldown section?

**Comment by x9nico** [comment]
In ViaVersion or OldCombatMechanics?

**Comment by gvlfm78** [comment]
In OldCombatMechanics. Does ViaVersion even have a setting for cooldown?

**Comment by x9nico** [comment]
For ViaViersion, I don't think so.

**Comment by x9nico** [comment]
It's not the subject, but I found an error to the start:
[22:26:57] [Server thread/INFO]: [OldCombatMechanics] Config file config.yml generated
[22:26:57] [Server thread/INFO]: Invalid type 'shield'
[22:26:57] [Server thread/ERROR]: [OldCombatMechanics] Plugin OldCombatMechanics v1.6.2 has failed to register events for class gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordBlocking because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.
[22:26:57] [Server thread/ERROR]: [OldCombatMechanics] Plugin OldCombatMechanics v1.6.2 has failed to register events for class gvlfm78.plugin.OldCombatMechanics.module.ModuleDisableOffHand because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.
[22:26:57] [Server thread/ERROR]: Error occurred while enabling OldCombatMechanics v1.6.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.createTeam(OCMMain.java:144) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.Team$Option
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 13 more

**Comment by gvlfm78** [comment]
Can you copy and paste the cooldown section of your config.yml here please?

**Comment by x9nico** [comment]
disable-attack-cooldown:
  # This is to disable the attack cooldown
  enabled: true
  worlds: []
  # What to set the attack speed to. Default for 1.9 is 4, at least 16 is needed for no cooldown.
  generic-attack-speed: 24

**Comment by Rayzr522** [comment]
You're running OldCombatMechanics on a pre-1.9 server. OCM does not run in 1.8 and below *because there is no attack cooldown in 1.8.* You do not need OCM if you're running a 1.8 server and allowing newer clients with ViaVersion. They won't have a cooldown because the combat is handled server-side, and the server is 1.8.

If you have any cooldown indicator client-side, then it's just that: client-side. It will not affect combat at all. The actual combat is handled server-side.
