### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to OldCombatMechanics

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#20]
OldCombatMechanics dev 17
Default config settings (new config generated).

```
[07:00:42] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to OldCombatMechanics v1.1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-910]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:773) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.CraftingManager.craft(CraftingManager.java:314) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.ContainerPlayer.a(ContainerPlayer.java:83) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.InventoryCrafting.setItem(InventoryCrafting.java:120) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.Slot.set(Slot.java:58) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.Container.a(Container.java:293) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1917) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-910]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-910]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_112]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_112]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleShieldCrafting.onItemCraft(ModuleShieldCrafting.java:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-910]
	... 22 more
[07:00:43] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to OldCombatMechanics v1.1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-910]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:773) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.CraftingManager.craft(CraftingManager.java:314) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.ContainerPlayer.a(ContainerPlayer.java:83) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.InventoryCrafting.splitStack(InventoryCrafting.java:112) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.SlotResult.a(SourceFile:97) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.ContainerPlayer.b(ContainerPlayer.java:169) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.Container.a(Container.java:263) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1917) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-910]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-910]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_112]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_112]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleShieldCrafting.onItemCraft(ModuleShieldCrafting.java:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-910]
	... 23 more
```

**Comment by Rayzr522** [comment]
I'll fix that for ya really quick. When I was writing that I just never expected an event to be called with no viewers...

**Comment by Rayzr522** [comment]
Wait a sec that isn't my module... XD

Whatever, still gonna fix it.

**Comment by Rayzr522** [comment]
@mibby 
https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/18/

See if that fixes it.

**Comment by gvlfm78** [comment]
This wasn't even my module at the start but I had to remake it to have the per-world feature. In what case does this get called with no viewers?
