### ISSUE TITLE
 Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6

### ISSUE THREAD

**Issue by leoncp9** [gvlfm78/BukkitOldCombatMechanics#208]
## Info

- Server version: paper spigot 1.12.2
- OldCombatMechanics version: 1.6.6
- Server log file: 
[04:43:16] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Paper-1508.jar:git-Paper-1508]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-1508.jar:git-Paper-1508]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1508.jar:git-Paper-1508]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[Paper-1508.jar:git-Paper-1508]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:947) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[Paper-1508.jar:git-Paper-1508]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[Paper-1508.jar:git-Paper-1508]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: packet_handler
	at gvlfm78.plugin.OldCombatMechanics.utilities.packet.PacketInjector.<init>(PacketInjector.java:43) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.utilities.packet.PacketManager.addListener(PacketManager.java:73) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModulePlayerCollisions.onPlayerLogin(ModulePlayerCollisions.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper-1508.jar:git-Paper-1508]
	... 15 more
Caused by: java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[Paper-1508.jar:git-Paper-1508]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[Paper-1508.jar:git-Paper-1508]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[Paper-1508.jar:git-Paper-1508]
	at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:274) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.utilities.packet.PacketInjector.attach(PacketInjector.java:69) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.utilities.packet.PacketInjector.<init>(PacketInjector.java:41) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.utilities.packet.PacketManager.addListener(PacketManager.java:73) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.module.ModulePlayerCollisions.onPlayerLogin(ModulePlayerCollisions.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper-1508.jar:git-Paper-1508]
	... 15 more
- OldCombatMechanics config file: 

## Problem Description
> can you fix this error on console?  Could not pass event PlayerJoinEvent to OldCombatMechanics v1.6.6

**Comment by I-Al-Istannen** [comment]
Can I get a list of all plugins and the output of `/version`?

**Comment by leoncp9** [comment]
private plugin sorry

**Comment by I-Al-Istannen** [comment]
Huh? That doesn't mean that you can post the server version and a list of plugins (names are rarely that private, or you blur it out), but in order to properly judge the problem I *need* to know about any other plugin that might modify the netty side of things and your exact server version.

You can also consider this ticket solved and live with the error, but that sounds like an inconvenient solution to me :)
