### ISSUE TITLE
Area Damage On Swords

### ISSUE THREAD

**Issue by AhmetDS** [gvlfm78/BukkitOldCombatMechanics#228]
## Info

- Server version: 1.12
- OldCombatMechanics version:1.6.6
- Server log file: 
- OldCombatMechanics config file: 

## Problem Description
> The area damage added in 1.9 is still not removed pls remove it

**Comment by AhmetDS** [comment]
no errors in logs and I didn't change the config file. sweep attack damages other enemies 1 heart  not main enemy main enemy damages by 7 heart if im holding diamond sword but other enemies can take damage

**Comment by gvlfm78** [comment]
Do the other move at all, or flash red?

**Comment by AhmetDS** [comment]
no knock back at other mobs

**Comment by gvlfm78** [comment]
Do they flash red, like the mob being hit does?

**Comment by AhmetDS** [comment]
no they dont https://dev.bukkit.org/projects/damage-indicator

**Comment by gvlfm78** [comment]
Could this be because OCM has the listener set on HIGHEST priority and thus only cancels the event after the damage indicator plugin has gotten the info?

**Comment by I-Al-Istannen** [comment]
Yes, that sounds right. Checking the source, that damage indicator plugin listens on priority NORMAL, although it should really listen on MONITOR. Not sure if we should adjust OCM, but listening on LOWEST sounds nicer than HIGHEST to me - I don't think a plugin would un-cancel the event.

In summary we can either change this to LOWEST or nag the plugin author to use MONITOR. The latter is a bit unlikely to help:
![grafik](https://user-images.githubusercontent.com/20284688/45059889-f31e3f80-b09d-11e8-9fd5-bb9625f645c5.png)

**Comment by gvlfm78** [comment]
Or find a similar plugin with the same features or even modify the plugin for him?

**Comment by I-Al-Istannen** [comment]
Why did you initially put the OCM listener to highest and not lowest? Lowest sounds like it would better fit what it does, as no other plugin will notice those unless it really wants to.

**Comment by gvlfm78** [comment]
Almost all of OCM's listeners are on HIGHEST to avoid messing up other plugin's functionality.

In this case, since all the module really does is cancel an event, it may be fine to set it to LOWEST.

**Comment by I-Al-Istannen** [comment]
It would be my preferred solution here, unless it causes some other conflicts. Not sure which ones that would be here. Some plugin would need to un-cancel damage events to reinstate the sweep damage. I don't know who would do that, but somebody might.

It really is the fault of the DamageIndicator plugin, but we could maybe be a bit more friendly to it unless you know a plugin that does un-cancel damage events.

**Comment by gvlfm78** [comment]
Alright, I have made this change. @AhmetDS please try [this test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/OldCombatMechanics/60/) and see if the DamageIndicator plugin still tells you other entities are being damaged.

**Comment by AhmetDS** [comment]
okey

**Comment by AhmetDS** [comment]
` [OldCombatMechanics] Config file config.yml generated
[13:46:08 ERROR]: Error occurred while enabling OldCombatMechanics v1.7.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.potion.PotionType.F¦RE_RES¦STANCE
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.potion.PotionType.valueOf(PotionType.java:1) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at gvlfm78.plugin.OldCombatMechanics.utilities.ConfigUtils.loadPotionDurationsList(ConfigUtils.java:73) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldPotionEffects.reload(ModuleOldPotionEffects.java:44) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldPotionEffects.<init>(ModuleOldPotionEffects.java:39) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.OCMMain.registerModules(OCMMain.java:117) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]`

**Comment by I-Al-Istannen** [comment]
Can you post your config.yml please?

**Comment by AhmetDS** [comment]
[myconfigbutitstxtforupload.txt](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2363252/myconfigbutitstxtforupload.txt)

**Comment by I-Al-Istannen** [comment]
Where are you from? Can you tell the language your server uses? I am in germany, so mine is de_DE, what is yours? I suspect a locale problem when upper casing the potion type as he gvlfm doesn't seem to have taken that into account.

If you do not want to tell me that, can you tell me what your upper case `i/I` looks like?

**Comment by AhmetDS** [comment]
im from turkish :/

**Comment by I-Al-Istannen** [comment]
```
jshell> "hey you there i am nice".toUpperCase($1);
$2 ==> "HEY YOU THERE İ AM NİCE"
```
Yea, that seems to be the problem. Languages are *mean*.

Can you try this [this](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2363259/OCM.zip) please?

**Comment by I-Al-Istannen** [comment]
Makes sense as the author did not set `ignoreCancelled` to true *and* doesn't check himself. That plugin is really broken.

You are likely better off finding another plugin, but if you insist you can try [this patch ](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2363280/DamageIndicator.zip) I made.

**Comment by AhmetDS** [comment]
can you use this damage indicator damage indicator doesnt supports 1.12.2 but this support
[Yeni WinRAR arşivi.zip](https://github.com/gvlfm78/BukkitOldCombatMechanics/files/2363342/Yeni.WinRAR.arsivi.zip)

**Comment by I-Al-Istannen** [comment]
That plugin looks like it will have the exact same problem. Can somebody tell me why none of these plugins seem to check whether the damage event is actually cancelled? That should also break with things like WorldGuard, Protection zones and whatever else.

Apart from the plugin you (leon) posted should work just fine on 1.12 (it does, as you've seen) and my patch *should* make it work correctly (i.e. ignore cancelled events).

@AhmetDS I would ask the author of that plugin you posted (if you know him) to stop spawning ArmorStands for cancelled events. It also might remove other ArmorStands if they are very close to the player/mob being damaged, if I followed that code correctly.

**Comment by AhmetDS** [comment]
damage indicator needs this plugin to work "https://dev.bukkit.org/projects/holoapi" but me posted damage indicator is dont need holoapi

**Comment by AhmetDS** [comment]
:/ nevermind i think this problem not causing oldcombatmechanics so how to delete sword sweep attack effect?

**Comment by I-Al-Istannen** [comment]
The effect on the client side? So the particles?

The answer is "you can't" as that is purely client side. OCM can disable the damage, but not the client side particles sadly.

**Comment by I-Al-Istannen** [comment]
@AhmetDS Any update? Have you tried the build I posted?

**Comment by AhmetDS** [comment]
yep it worked

**Comment by AhmetDS** [comment]
thx man
