### ISSUE TITLE
OldCombatMechanics Issue

### ISSUE THREAD

**Issue by NoopyyGaming** [gvlfm78/BukkitOldCombatMechanics#231]
## Info

- Server version: 1.9 --> 1.13 (with ViaVersion)
- OldCombatMechanics version: 1.6.5
- Server log file: latest.log

## Problem Description
> [13:56:38] [Server thread/INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v1.6.5
[13:56:38] [Server thread/INFO]: [OldCombatMechanics] Config file config.yml generated
[13:56:38] [Server thread/ERROR]: [OldCombatMechanics] Plugin OldCombatMechanics v1.6.5 has failed to register events for class gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordBlocking because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.
[13:56:38] [Server thread/ERROR]: [OldCombatMechanics] Plugin OldCombatMechanics v1.6.5 has failed to register events for class gvlfm78.plugin.OldCombatMechanics.module.ModuleDisableOffHand because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.
[13:56:38] [Server thread/ERROR]: Error occurred while enabling OldCombatMechanics v1.6.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.createTeam(OCMMain.java:147) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[server.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [server.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [server.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [server.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [server.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [server.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [server.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [server.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.Team$Option
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-7d15d07-c194444]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 13 more

Which one do i must use for my 1.9 server ?

**Comment by I-Al-Istannen** [comment]
![grafik](https://user-images.githubusercontent.com/20284688/45030337-c8a39680-b04b-11e8-8523-d305e1234d68.png)
Your spigot jar seems to be broken. Does the rest of the server work? Do you use some (weird in this case) fork of spigot?

**Comment by NoopyyGaming** [comment]
Rest of the server ? everything work, only the plugin not, and i don't think that i'am using some weird words of fork spigot

**Comment by I-Al-Istannen** [comment]
Can you try to rebuild the spigot jar with BuildTools and see if the problems persist? If yes, can you open the server jar with a ZIP viewer (7Zip, WinRar, whatever) and see if you can find the following files:
```
org/bukkit/scoreboard/Team$Option.class
org/bukkit/event/player/PlayerSwapHandItemsEvent.class
```

**Comment by NoopyyGaming** [comment]
I got it working right now, i've downloaded another spigot.jar which make the plugin working good :) but anyway, thanks for your answer

**Comment by I-Al-Istannen** [comment]
I would advise against downloading spigot jars and instead follow the official docs [here](https://www.spigotmc.org/wiki/buildtools/).

Nice you got it to work though :) If this is solved, consider closing the issue.
