### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [gvlfm78/BukkitOldCombatMechanics#26]
Hello,

I have this error on Spigot 1.11 : 
[11:15:48] [Server thread/ERROR]: Could not pass event BlockDispenseEvent to OldCombatMechanics v1.1.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:63) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DispenseBehaviorItem.b(DispenseBehaviorItem.java:26) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.BlockDropper.dispense(BlockDropper.java:41) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.BlockDispenser.b(BlockDispenser.java:113) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:740) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:250) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:790) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.block.CraftDropper cannot be cast to org.bukkit.block.Dispenser
	at com.codingforcookies.armourequip.ArmourListener.dispenserFireEvent(ArmourListener.java:188) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1241.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
	... 15 more

Thanks to fix it. :D

**Comment by gvlfm78** [comment]
Should be fixed in test version [30](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/30/)
