### ISSUE TITLE
MAGIC is not applicable (EntityDamageByEntityEvent)

### ISSUE THREAD

**Issue by DenisJ9798** [gvlfm78/BukkitOldCombatMechanics#307]
```
[16:33:51] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to OldCombatMechanics v1.7.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1613]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1613]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1613]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1613]
at net.dmulloy2.swornguns.types.Bullet.explosionDamage(Bullet.java:431) ~[?:?]
at net.dmulloy2.swornguns.types.Bullet.onHit(Bullet.java:311) ~[?:?]
at net.dmulloy2.swornguns.types.Bullet.remove(Bullet.java:250) ~[?:?]
at net.dmulloy2.swornguns.types.Bullet.tick(Bullet.java:199) ~[?:?]
at net.dmulloy2.swornguns.SwornGuns$UpdateTimer.run(SwornGuns.java:349) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1613]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1613]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1613]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1613]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.UnsupportedOperationException: MAGIC is not applicable to CraftPlayer{name=mananam}
at org.bukkit.event.entity.EntityDamageEvent.setDamage(EntityDamageEvent.java:89) ~[patched_1.12.2.jar:git-Paper-1613]
at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onEntityDamage(ModuleOldArmourStrength.java:64) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor209.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1613]
... 15 more
```

**Comment by gvlfm78** [comment]
Please check [test version 47](https://ci.rayzr.dev/job/OldCombatMechanics/47/) if the issue is still present.

**Comment by Tigerpanzer02** [comment]
With 47 it seems to be fine on my server

**Comment by ZEROOblivious** [comment]
25.05 01:42:12 [Server] INFO [OldCombatMechanics] Enabling OldCombatMechanics v1.7.2beta 25.05 01:42:12 [Server] INFO [OldCombatMechanics] Config file config.yml generated 25.05 01:42:12 [Server] INFO [OldCombatMechanics] OldCombatMechanics v1.7.2beta has been enabled

Version 47 Seems to be stabilizing; Not many error as originally having. . . Going through the config and changing some settings.

**Comment by Tigerpanzer02** [comment]
`[20:39:16] [Server thread/ERROR]: Could not pass event EntityDamageEvent to OldCombatMechanics v1.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:566) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:631) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:617) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityArmorStand.damageEntity(EntityArmorStand.java:420) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:210) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:321) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1873) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityArmorStand.B_(EntityArmorStand.java:570) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedOperationException: MAGIC is not applicable to CraftArmorStand
	at org.bukkit.event.entity.EntityDamageEvent.setDamage(EntityDamageEvent.java:89) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldArmourStrength.onEntityDamage(ModuleOldArmourStrength.java:65) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	... 22 more`

Hey I have the error again.

**Comment by gvlfm78** [comment]
@Tigerpanzer02 please try test build [50](https://ci.rayzr.dev/job/OldCombatMechanics/50)

**Comment by Tigerpanzer02** [comment]
I can test it on weekend
