### ISSUE TITLE
NoClassDefFoundError: net/gravitydevelopment/updater/Updater

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#33]
OCM dev 43, generated new config. Errored as soon as I logged into my test server.

```
[06:56:26] [Craft Scheduler Thread - 7/WARN]: [OldCombatMechanics] Plugin OldCombatMechanics v1.1.2 generated an exception while executing task 131
java.lang.NoClassDefFoundError: net/gravitydevelopment/updater/Updater
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.getUpdateMessages(OCMUpdateChecker.java:36) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.sendUpdateMessages(OCMUpdateChecker.java:50) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMListener$1.run(OCMListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1009]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1009]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1009]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: net.gravitydevelopment.updater.Updater
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1009]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1009]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	... 9 more

```

**Comment by gvlfm78** [comment]
Does this still happen with the newer test builds?

**Comment by gvlfm78** [comment]
@mibby Could we please know if the implemented fix worked?

**Comment by mibby** [comment]
@gvlfm78 Apologies, just got back from the holidays.

Error trying to load dev build 45.
```
[10:43:45] [Server thread/ERROR]: Could not load 'plugins\OldCombatMechanics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin version formatted wrong!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [patched_1.11.2.jar:git-Paper-1021]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:208) [patched_1.11.2.jar:git-Paper-1021]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.2.jar:git-Paper-1021]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Plugin version formatted wrong!
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.getVersionNumbers(SpigotUpdateChecker.java:101) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.isUpdateOut(SpigotUpdateChecker.java:110) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.shouldUpdate(SpigotUpdateChecker.java:94) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.versionCheck(SpigotUpdateChecker.java:85) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.run(SpigotUpdateChecker.java:78) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.SpigotUpdateChecker.<init>(SpigotUpdateChecker.java:49) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.<init>(OCMUpdateChecker.java:22) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMMain.<init>(OCMMain.java:22) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_112]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.11.2.jar:git-Paper-1021]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.11.2.jar:git-Paper-1021]
	... 6 more
```

**Comment by gvlfm78** [comment]
Yeah I know about that error but I'm currently working on something and so haven't commited the fix yet

**Comment by mibby** [comment]
All good, just letting you know. :)

**Comment by mibby** [comment]
Did you want me to open it as a new ticket?

**Comment by gvlfm78** [comment]
Normally, yes, but I've already found out about and fixed that error, just haven't committed the fix, so no.

**Comment by mibby** [comment]
👍
