### ISSUE TITLE
NPE when exiting brewing stand with no fuel

### ISSUE THREAD

**Issue by TheIntelloBox** [gvlfm78/BukkitOldCombatMechanics#38]
[17:06:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to OldCombatMechanics v1.1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1844) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException

**Comment by gvlfm78** [comment]
I think this is the same error others reported but not here on GitHub. You did the right thing in reporting here, but IIRC this should have been fixed in one of the test versions. I therefore ask you to check if that it the case in the [latest test version](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/56/).

**Comment by TheIntelloBox** [comment]
Thanks ! :D
