### ISSUE TITLE
Error When Joining

### ISSUE THREAD

**Issue by Waffles2112** [gvlfm78/BukkitOldCombatMechanics#41]
This error appears in the console when a player joins the server but to my testing has no affect on gameplay

[21:55:22 WARN]: [OldCombatMechanics] Plugin OldCombatMechanics v1.1.2 generated an exception while executing task 369
java.lang.NoClassDefFoundError: net/gravitydevelopment/updater/Updater
        at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.getUpdateMessages(OCMUpdateChecker.java:36) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.sendUpdateMessages(OCMUpdateChecker.java:50) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.OCMListener$1.run(OCMListener.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1059]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1059]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1059]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by gvlfm78** [comment]
This is caused by the plugin not containing the updater class. This means that taking a build from the jenkins server should work. Therefore, could you try the [latest test build](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/lastSuccessfulBuild/) and tell us if the error is still present?
