### ISSUE TITLE
NoClassDefFoundError: net/gravitydevelopment/updater/Updater

### ISSUE THREAD

**Issue by mibby** [gvlfm78/BukkitOldCombatMechanics#44]
OCM dev 63

```
[03:45:54] [Craft Scheduler Thread - 4/WARN]: [OldCombatMechanics] Plugin OldCombatMechanics v1.2.0 generated an exception while executing task 124
java.lang.NoClassDefFoundError: net/gravitydevelopment/updater/Updater
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.getUpdateMessages(OCMUpdateChecker.java:36) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMUpdateChecker.sendUpdateMessages(OCMUpdateChecker.java:50) ~[?:?]
	at gvlfm78.plugin.OldCombatMechanics.OCMListener$1.run(OCMListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1062]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1062]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.gravitydevelopment.updater.Updater
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1062]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 9 more
```

**Comment by gvlfm78** [comment]
Could you try build [#64](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/64/)

**Comment by mibby** [comment]
Seems to be working now. No more error at start-up with update-check enabled.
