### ISSUE TITLE
Per-world function does not work anymore

### ISSUE THREAD

**Issue by ItsMennyo** [gvlfm78/BukkitOldCombatMechanics#53]
When you first enable "disable-attack-cooldown:" to have standing in the world and ale than functional: it only has to work then you have yet another world in a particular world. Rejoin does not work and the server restart does also not work.

I personally think that the "worlds" feature is dead because when I turn "generic-attack speed: 4" to set in all worlds and then "generic-attack speed: 128" do a particular world than all worlds again at the rate of 128...

Sorry for my bad English... I use Google Translate 😋

**Comment by gvlfm78** [comment]
Well Google Translate might need some improvements because I didn't understand any of that

**Comment by ItsMennyo** [comment]
Briefly summarized:

If I "disable-attack-cooldown:" to one world than I have anywhere.
And I have tried different ways to get it back but I can not explain or Google Translate makes it what I say before...

Hope this is clearer :P

**Comment by ItsMennyo** [comment]
EDIT: if you have something on in the config it is in all the worlds so I guess the "world:" option is dead or something...

**Comment by ItsMennyo** [comment]
Sorry to insist, but it starts to get a little rush because all checks are now totally bugged???

I also tried an older version to turn it back but it seems totally pitted be. Even if people join the server while the plug is no longer active people still get all the checks that were in the config???

**Comment by gvlfm78** [comment]
What version of the plugin are you using? What does your config contain in
the parts with worlds:?

**Comment by ItsMennyo** [comment]
I first used 1.2.0 and it worked fine when I update to 1.3.0+ and everything was so sudden and I also tried the latest Jenkins build (#75) and that did not work.

So my config currently looks: https://pastebin.com/GKb2JrdA

And I'm already so tried (throughout):
`  worlds:
  - spawn
  - kitpvp
  - skyblock
  - skyblock_nether`

and so:
`  worlds:
    - spawn
    - kitpvp
    - skyblock
    - skyblock_nether`

But not all work...

**Comment by ItsMennyo** [comment]
And now I also get this spammed in my console:

`[10:50:43 ERROR]: Could not pass event EntityDamageByEntityEvent to OldCombatMechanics v1.3.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:621) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.EntityItemFrame.damageEntity(EntityItemFrame.java:38) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.EntityHanging.t(EntityHanging.java:167) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:934) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1134) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1576) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: SWEEPING_EDGE
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordSweep.onSwordAttack(ModuleSwordSweep.java:45) ~[?:?]
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleSwordSweep.onEntityDamaged(ModuleSwordSweep.java:37) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        ... 23 more`

**Comment by gvlfm78** [comment]
What version of bukkit/spigot do you have?

**Comment by ItsMennyo** [comment]
`[11:31:47 INFO]: This server is running CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)                                                                                            [11:31:47 INFO]: Checking version, please wait...                                                                                                                                                                                            [11:31:47 INFO]: You are 361 version(s) behind`

**Comment by gvlfm78** [comment]
I see. You are getting that error in the console because the sweeping edge enchantment didn't exist in 1.9. I will have to add a check for that.

**Comment by ItsMennyo** [comment]
[Okay, and what about the world function](https://github.com/gvlfm78/BukkitOldCombatMechanics/issues/53#issuecomment-294433270)?

**Comment by gvlfm78** [comment]
I need to see if I have the same problem or not. Currently I don't so I will have to do some testing. Are you saying that when you enable modules in only some worlds they are enabled in all of them? What modules specifically does this happen with?

**Comment by ItsMennyo** [comment]
I'll just make a video about this...

**Comment by ItsMennyo** [comment]
Here's the video: https://www.youtube.com/watch?v=3dI0sDTyB44&feature=youtu.be

And in the end I visit the KitPvP world go there "old-armor-strength:" should work then does not even unless you re doing to your armor...

**Comment by gvlfm78** [comment]
Both bugs should now be fixed in [build #76](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/76/). I didn't get round to test on a 1.9 server the swing attack module so please tell me if the bug is fixed or not.

**Comment by ItsMennyo** [comment]
It works! All the worlds that were not configured the changes are now gone and what it is supposed to work is simply work. And the error in "disable-sword-sweep:" is gone! Thanks for the fix and my players will thank you 😋
