### ISSUE TITLE
And this is yet another error...

### ISSUE THREAD

**Issue by ItsMennyo** [gvlfm78/BukkitOldCombatMechanics#58]
And this is yet another error...

`[16:19:09 ERROR]: Could not pass event ProjectileHitEvent to OldCombatMechanics v1.4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:779) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.EntityFishingHook.m(EntityFishingHook.java:202) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.World.g(World.java:1592) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.ProjectileHitEvent.getHitEntity()Lorg/bukkit/entity/Entity;
        at gvlfm78.plugin.OldCombatMechanics.module.ModuleFishingKnockback.onRodLand(ModuleFishingKnockback.java:43) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor303.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        ... 14 more`

**Comment by gvlfm78** [comment]
Can you try build [#79](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/79/)? I added both the old and new pieces of code for compatibility.
