### ISSUE TITLE
java.util.zip.ZipException: invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by christer88** [gvlfm78/BukkitOldCombatMechanics#66]
[17:51:07] [Server thread/ERROR]: Could not load 'plugins/OldCombatMechanics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	... 5 more

---

[17:51:07] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

This error came with plugin version 1.4.1 it seems.

**Comment by Rayzr522** [comment]
Sounds like the file is corrupt. Please try redownloading.
