### ISSUE TITLE
Error when opening GUI

### ISSUE THREAD

**Issue by T1MOXA** [gvlfm78/BukkitOldCombatMechanics#80]
```
[Server thread/ERROR]: Could not pass event InventoryOpenEvent to OldCombatMechanics v1.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:755) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:786) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at me.clip.deluxemenus.menu.Menu$1$2.run(Menu.java:200) [DeluxeMenus-1.9.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at gvlfm78.plugin.OldCombatMechanics.module.ModuleOldBrewingStand.onInventoryOpen(ModuleOldBrewingStand.java:32) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	... 14 more
```

**Comment by T1MOXA** [comment]
In other menus also have the same error

> test build 119, please tell me if the issue is still present.

Thanks, will check

**Comment by T1MOXA** [comment]
Yes, it's all good now, thanks :)
