### ISSUE TITLE
Can't take off armour with "old-armour-strength" module enabled and ItemFixer plugin installed

### ISSUE THREAD

**Issue by T1MOXA** [gvlfm78/BukkitOldCombatMechanics#81]
Server version 1.12
Client version 1.8

**Comment by gvlfm78** [comment]
I'm not sure what this means, does it mean you are unable to take your armour off when the module is enabled? (By clicking, shift clicking??)

**Comment by T1MOXA** [comment]
Yes, if they are wearing I can't take them off

**Comment by gvlfm78** [comment]
In what ways are they trying to take it off?
Do they get any error? Does it teleport back to the previous slot or not move at all?

**Comment by T1MOXA** [comment]
Error:
Could not pass event ArmourEquipEvent to OldCombatMechanics v1.5.0 
org.bukkit.event.EventException: null 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at com.codingforcookies.armourequip.ArmourListener.onInventoryClick(ArmourListener.java:142) [OldCombatMechanics.jar:?] 
at sun.reflect.GeneratedMethodAccessor755.invoke(Unknown Source) ~[?:?] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111] 
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111] 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2098) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111] 
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37] `

**Comment by gvlfm78** [comment]
This is Bukkit doing strange things to inventories when in creative again...
I have added a check in [test build 120](https://jenkins-gvl.rhcloud.com/job/OldCombatMechanics/120/) that excludes creative inventories from the module

**Comment by gvlfm78** [comment]
Do you still get this error in the latest test version?

**Comment by T1MOXA** [comment]
Yes, the bug is still there.

**Comment by gvlfm78** [comment]
What gamemode are you in when this happens?

Do you still get an error? Is it the same or different?

**Comment by T1MOXA** [comment]
No, there is no error.
Use gamemode 0

**Comment by T1MOXA** [comment]
I think I found what the problem is.
https://www.spigotmc.org/resources/itemfixer-remove-cheats-items-from-your-server.34250/

**Comment by gvlfm78** [comment]
That plugin would definitely conflict as it tries to remove NBT tags OCM placed on the items

**Comment by BurnyDaKath** [comment]
Elytra module may cause issues with following lines, because check if the item is elytra happens later.
```Java
if(e.getSlot() == 38){
	e.setCancelled(true);
	return;
}
```

**Comment by gvlfm78** [comment]
@BurnyDaKath That's a different issue, #95 , which I believe is fixed but never received confirmation.

**Comment by gvlfm78** [comment]
There's not much that can be done here as the plugin remove OCM's items and hinders its functionality.
