### ISSUE TITLE
Armor Equip Event

### ISSUE THREAD

**Issue by CryptoMorin** [gvlfm78/BukkitOldCombatMechanics#82]
Error. Unknown source.
Where does it come from?

[21:12:40] [Server thread/ERROR]: Could not pass event ArmourEquipEvent to OldCombatMechanics v1.4.2
org.bukkit.event.EventException: null
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-0869666-03f1e37]
 at com.codingforcookies.armourequip.ArmourListener.onInventoryClick(ArmourListener.java:91) [OldCombatMechanics.jar:?]
 at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-0869666-03f1e37]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-0869666-03f1e37]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-0869666-03f1e37]
 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-0869666-03f1e37]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: java.lang.Inte

**Comment by CryptoMorin** [comment]
This Issue is already reported.
